spring:
  datasource:
    url: jdbc:h2:mem:backpack
    driver-class-name: org.h2.Driver
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: update
    defer-datasource-initialization: true
  h2:
    console:
      enabled: true
      path: /h2-console